# Metadata for the Smart-Plugin
plugin:
    # Global plugin attributes
    type: web                      # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Abfrage der Reisezeit über die kostenlose Google Directions API. Für einen eigenen Key siehe <a href="https://developers.google.com/maps/documentation/directions/intro?hl=de#traffic-model" target="_blank">https://developers.google.com/maps/documentation/directions/intro?hl=de#traffic-model</a>.'
        en: 'Get travel times and directions via the (free) Google Directions API. For your own key see <a href="https://developers.google.com/maps/documentation/directions/intro?hl=de#traffic-model" target="_blank">https://developers.google.com/maps/documentation/directions/intro?hl=de#traffic-model</a>'
    maintainer: psilo909
#    tester:                        # Who tests this plugin?
    keywords: google directions, travel times, routing information
    documentation: http://smarthomeng.de/user/plugins_doc/config/traffic.html
    support: https://knx-user-forum.de/forum/supportforen/smarthome-py/1048446-traffic-plugin-support-thread

    version: 1.3.0.1               # Plugin version
    sh_minversion: 1.3             # minimum shNG version to use this plugin
#    sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: False          # plugin supports multi instance
    classname: Traffic             # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml
    apikey:
        type: str
        mandatory: True
        description:
            de: 'Persönlicher API Key die kostenlose "Google Directions API". Für einen eigenen Key siehe <a href="https://developers.google.com/maps/documentation/directions/intro?hl=de#traffic-model" target="_blank">https://developers.google.com/maps/documentation/directions/intro?hl=de#traffic-model</a>.'
            en: 'For accessing the free "Google Directions API" you need a personal api key. For your own key see <a href="https://developers.google.com/maps/documentation/directions/intro?hl=de#traffic-model" target="_blank">https://developers.google.com/maps/documentation/directions/intro?hl=de#traffic-model</a>'

    language:
        type: str
        default: 'de'
        description:
            de: '(optional) Sprache, in der bspw. Routinganweisungen bezogen werden sollen. Default: deutsch.'
            en: '(optional) Language to retrieve routing information. Default: German (de)'
    
item_attributes:
    # Definition of item attributes defined by this plugin
    
