# Metadata for the Smart-Plugin
plugin:
    # Global plugin attributes
    type: web                      # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Abfrage der Abfahrten in Stationen der Münchner Verkehrsbetriebe (MVG)'
        en: 'Retrieval of departure times of stations within the Münchner Verkehrsbetriebe (MVG)'
    maintainer: psilo909
#    tester:                        # Who tests this plugin?
    keywords: public transport, departure times, Munich, München
    documentation: http://smarthomeng.de/user/plugins_doc/config/mvg_live.html
    support: https://knx-user-forum.de/forum/supportforen/smarthome-py/1108867-neues-plugin-mvg_live

    version: 1.3.0.1               # Plugin version
    sh_minversion: 1.3             # minimum shNG version to use this plugin
#    sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: False          # plugin supports multi instance
    classname: MVG_Live            # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml
    
item_attributes:
    # Definition of item attributes defined by this plugin
    
